# Dockerfile : sert à configurer le conteneur pour lancer l'application

# Starting with an base image (already existing in Docker Hub) with alpine version
FROM node:20-alpine

# Working  directory /client inside the container
WORKDIR /client

# Copie de package.json et dans le conteneur
COPY ./package*.json ./

# On lance NPM pour l'installation des dépendances
RUN npm install

# Copie du reste des fichiers du dossier client dans le conteneur
COPY  . .


EXPOSE 3000


