
services:
  client :
      # On définit une image de Node.js comme base en indiquant la version utilisée
      container_name : Client
      # user: docker:docker
      build:
        context: ./client
        dockerfile: ./dockerfile.client

      # commande a executer avant de lancer le serveur
      # RUN npm install

      # Lancement du script "npm run dev" pour démarrer l'application
      # command : ["npm","run", "dev"]
      volumes:
        - ./client:/client
        - /client/node_modules
      command: npm run dev
      
      environment:
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        - SECRET_KEY=${SECRET_KEY}
        - DEV_ENV= ${DEV_ENV}
        - API_KEY= ${API_KEY}

      depends_on:
        - db
      ports:
      - "3000:3000"

  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:5432"
    
    volumes:
      - ./client/database/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
