services:
  - type: web
    name: blablabook
    runtime: docker
    docker:
      registry: docker.io
      repo: lukevideo/blablabook
      tag: latest
    region: oregon
    plan: free
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false